---
version: 1.0
root: "./.tests/cloud_test/"
timeout: 7200  # 2 hour total total timeout
shuffle-enabled: true
statistics:
  enabled: true
  interval: 60  # 60 seconds for statistics
import:
  - cloudtest/aws.yaml
  - cloudtest/tests.yaml

retest:  # Allow to do test re-run if some kind of failures are detected, line CNI network plugin errors.
  count: 1  # Allow 1 times to do restart
  warmup-time: 15  # Put 15 seconds warmup for cluster instance to be used again.
  allowed-retests: 2  # If cluster instance have few attempts with retest requests one after another, we need to restart cluster.
  pattern:
    - "NetworkPlugin cni failed to set up pod"    # Error in AWS dur to leak of IPs or not ability to assign them.
    - "etcdserver: request timed out"  # Error in any could, reason unknown.
    - "unable to establish connection to VPP (VPP API socket file /run/vpp/api.sock does not exist)"  # a VPP is not started, it will be re-started in general, but will cause test fail.
    # Sometimes (rarely) docker registry is unavailable for a moment
    - "Error response from daemon: Get https://.*docker.io/.*: dial tcp: lookup registry"
    - "Error response from daemon: Get https://.*docker.io/.*: net/http: request canceled while waiting for connection"
    - "Failed create pod sandbox"
reporting:
  junit-report: "results/junit.xml"
health-check:
  - message: "Branch is not up to date"
    interval: 60  # 1 minute
    run: |
      echo "Health check!"
