---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: NSM_CLUSTER_NAME
  region: NSM_REGION
  version: "1.27"

kubernetesNetworkConfig:
  ipFamily: IPv4

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: aws-ebs-csi-driver
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy

iam:
  withOIDC: true

managedNodeGroups:
  - name: NSM_NODEGROUPS_NAME
    instanceType: t3.xlarge
    desiredCapacity: 2
